workspace:
  base: /go
  path: src/git.jonasfranz.software/JonasFranzDEV/gitea-github-migrator

clone:
  git:
    image: plugins/git:1
    depth: 50
    tags: true

pipeline:
  deps:
    image: golang:1.10
    pull: true
    environment:
      GOPATH: /go
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure
  test:
    image: golang:1.10
    pull: true
    environment:
      GOPATH: /go
    commands:
      - go get -u golang.org/x/lint/golint
      - golint -set_exit_status $(go list ./...)
      - go vet ./...
      - go test -cover ./...
  static:
    image: golang:1.10
    pull: true
    environment:
      GOPATH: /go
    commands:
      - go get -u github.com/mitchellh/gox
      - gox -ldflags "-X main.version=${DRONE_TAG##v} -X main.build=${DRONE_BUILD_NUMBER}" -output "releases/gitea-github-migrator_{{.OS}}_{{.Arch}}"
    when:
      event: [ tag ]
  gitea:
    image: plugins/gitea-release:latest
    pull: true
    base_url: "https://git.jonasfranz.software"
    secrets: [ gitea_token ]
    files:
      - releases/*
    checksum:
      - sha256
      - md5
    when:
      event: [ tag ]