[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "myuserinfo"
  name = "code.gitea.io/sdk"
  source = "github.com/JonasFranzDEV/go-sdk"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "github.com/google/go-github"
  version = "15.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/jinzhu/configor"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "1.11.1"

[[constraint]]
  branch = "master"
  name = "github.com/adam-hanna/randomstrings"

[[constraint]]
  name = "gopkg.in/macaron.v1"
  version = "1.3.1"

[[constraint]]
  branch = "master"
  name = "github.com/go-macaron/session"

[[constraint]]
  branch = "master"
  name = "github.com/go-macaron/binding"