[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "code.gitea.io/sdk"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "github.com/google/go-github"
  version = "15.0.0"