// tslint:disable
/**
 * Gitea GitHub Migrator API
 * the purpose of this application is to provide access to the migrator backend
 *
 * OpenAPI spec version: 0.0.9
 * Contact: info@jonasfranz.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";
